# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wowml.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bwowml.proto\x12\x05wowml\x1a\x1bgoogle/protobuf/empty.proto\"2\n\rActionRequest\x12!\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x10.wowml.MlCommand\" \n\x0fMlStatusRequest\x12\r\n\x05token\x18\x01 \x01(\t\"(\n\x0fImportMlRequest\x12\x15\n\rbase64StrFile\x18\x01 \x01(\x0c\"2\n\x0fResponseMessage\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x16\n\x08MlStatus\x12\n\n\x02id\x18\x01 \x01(\x05*Z\n\tMlCommand\x12\x0b\n\x07PREDICT\x10\x00\x12\n\n\x06\x45XPORT\x10\x01\x12\x12\n\x0e\x43REATE_DATASET\x10\x02\x12\x07\n\x03LOG\x10\x03\x12\x17\n\x13\x44OWNLOAD_CHECKPOINT\x10\x04\x32\xba\x01\n\rWowController\x12\x32\n\x05Setup\x12\x16.wowml.MlStatusRequest\x1a\x0f.wowml.MlStatus\"\x00\x12:\n\x06Import\x12\x16.wowml.ImportMlRequest\x1a\x16.wowml.ResponseMessage\"\x00\x12\x39\n\x07\x41\x63tions\x12\x14.wowml.ActionRequest\x1a\x16.wowml.ResponseMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wowml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MLCOMMAND']._serialized_start=255
  _globals['_MLCOMMAND']._serialized_end=345
  _globals['_ACTIONREQUEST']._serialized_start=51
  _globals['_ACTIONREQUEST']._serialized_end=101
  _globals['_MLSTATUSREQUEST']._serialized_start=103
  _globals['_MLSTATUSREQUEST']._serialized_end=135
  _globals['_IMPORTMLREQUEST']._serialized_start=137
  _globals['_IMPORTMLREQUEST']._serialized_end=177
  _globals['_RESPONSEMESSAGE']._serialized_start=179
  _globals['_RESPONSEMESSAGE']._serialized_end=229
  _globals['_MLSTATUS']._serialized_start=231
  _globals['_MLSTATUS']._serialized_end=253
  _globals['_WOWCONTROLLER']._serialized_start=348
  _globals['_WOWCONTROLLER']._serialized_end=534
# @@protoc_insertion_point(module_scope)
